[package]
name = "encodings"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures-lite = "2.6.0"
glommio = "0.9.0"
prost = "0.13.5"
prost-types = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"
